apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    run: ftps
spec:
  type: LoadBalancer
  ports:
  - port: 21
    targetPort: 21
    protocol: TCP
    name: ftp-command
  - port: 20
    targetPort: 20
    protocol: TCP
    name: ftp-file
  selector:
    app: ftps
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: custom_ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 20
