apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    run: wordpress
spec:
  type: LoadBalancer
  ports:
    - port: 5050
      name: http
      targetPort: 5050
      protocol: TCP
  selector:
    app: ft_service
    tier: wordpress
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: ft_service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: ft_service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ft_service
      tier: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ft_service
        tier: wordpress
    spec:
      containers:
      - image: custom_wp
        imagePullPolicy: Never
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
          - containerPort: 9000
          - containerPort: 5050
            name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim