FROM ALPINE:LINUX

MAINTAINER nieyraud

#############################
# INSTALLING DEPENDENCIES	#
#############################

RUN 

#############################
#	CLEANING CONTAINER		#
#############################


#############################
#	LAUNCHING COMMAND		#
#############################

CMD